# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wenting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('jobs', models.CharField(max_length=20)),
            ],
        ),
    ]
